services:
  postgres:
    image: postgres:15
    container_name: simplebox-postgres
    environment:
      POSTGRES_DB: simplebox_db
      POSTGRES_USER: simplebox_user
      POSTGRES_PASSWORD: simplebox_pass
    ports:
      - "5434:5432"
    volumes:
      - simplebox-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simplebox_user -d simplebox_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/simplebox_db
      SPRING_DATASOURCE_USERNAME: simplebox_user
      SPRING_DATASOURCE_PASSWORD: simplebox_pass
    restart: unless-stopped

volumes:
  simplebox-postgres-data: